### ISSUE TITLE
Bug in webpage subprocess stderr parsing

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot#222]
From https://github.com/manubot/rootstock/runs/597802012#step:8:33

```python-traceback
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/manubot/bin/manubot", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/command.py", line 230, in main
    function(args)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/webpage/webpage_command.py", line 17, in cli_webpage
    ots_upgrade(args)
  File "/usr/share/miniconda3/envs/manubot/lib/python3.7/site-packages/manubot/webpage/webpage_command.py", line 198, in ots_upgrade
    elif not process.stderr.strip() == "Success! Timestamp complete":
AttributeError: 'NoneType' object has no attribute 'strip'
##[error]Process completed with exit code 1.
```

Error in:

https://github.com/manubot/manubot/blob/9c33b7a53f60aa5aba42424b925af0c32ea561fb/manubot/webpage/webpage_command.py#L198-L199

**Comment by dhimmel** [comment]
Likely caused by https://github.com/manubot/manubot/commit/b4a6238dd87327e1f451fa23959753ad27c7deee#diff-5fa0f519e1dd0132a14e1c02c0e61643
